FROM apache/airflow:2.9.0-python3.12

RUN pip install -r requirements.txt

RUN python3.12 -m venv venv && \                                                                                                                                                     ~/_code/github/scd_dag_factory
source venv/bin/activate && \
pip install --upgrade pip \



